### PR TITLE
Add man pages

### PR DESCRIPTION
**Pull request by graahnul-grom**

### CODE REVIEW

**Review by vzh — APPROVED** [review]

**Comment by graahnul-grom** [comment]
@vzh How do I update `index.html`? I thought it supposed
to be done automatically.

**Comment by vzh** [comment]
I used export from emacs org mode.  In future, we could use some automation, probably deployment using travis or gh actions.  Let's discuss this somewhere else.

**Comment by graahnul-grom** [comment]
there is the `after_success` target in `travis`:
https://stackoverflow.com/questions/19845679/build-with-travis-ci-and-push-some-files-folder-to-another-repository

**Comment by vzh** [comment]
We need investigate this possibility.  Meanwhile I updated the site manually.

**Comment by graahnul-grom** [comment]
Thank you.

**Comment by graahnul-grom** [comment]
It would be nice to add a direct link to https://lepton-eda.github.io
either in readme.md or repo description ("About").

**Comment by vzh** [comment]
Done in readme.  Could not edit it in the About pop-up for some reason though.

**Comment by vzh** [comment]
Huh, found how to do it :-)

**Pull request merged**
